spring.application.name=ems-backend
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/EMSNew
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.web.pageable.default-page-size=10
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hrtektalis@gmail.com
spring.mail.password=hdmc jkdk krvq fiok
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
ems.jwt.secret=Z3V2d3dxd3Vpd2V1d2V1aXdlcXVpd2V1cXVpd2V1cXVpd2V1
ems.jwt.expiration=900000
ems.jwt.refreshExpiration=8640000000
logging.level.root=WARN
logging.level.com.employee=INFO
logging.level.org.springframework.security=WARN
